# **NUMPY FULL REVISION**

## **01.Numpy Basics**

* **It is a fundamental package for scientific computing in Python**
* Numpy stores data in the form of an n-dimensional Array
* Array are data structures that stores data/items of the same type only

* **np.array**(list/tuple/set,ndmin=(Dimension type),dtype=(data_type of all items in the array))
* **array.ndmin** --> To get the dimesnion idea of the array
* A **matrix is a specialized 2-D array** that retains its 2-D nature through operations.
* **np.asarray** --> creates a view of the array of hpow it will look if converted to array
                1. **Creates a view if possible, otherwise a copy**
                2. **More memory efficient (avoids unnecessary copies)**
                3. **Avoids copying if the data is already suitable for a NumPy array**

* **np.fromfunction(function,dimension(X*Y))** --> Creating an array from a function
    * best to use with lambda function for quick creation of array

* **<array_obj>.shape** ---> Gives the total number of elements present in the Numpy Array
* **<array_obj>.ndim** ---> Gives the Dimensions of the Array
* **np.asanyarray** ---> This function will convert only those object into which are not in the form of an Array (like list , tuple , set) . If the Object passed is already an Array or Sub-class of an Array(like matrices) it will leave as it is won't convert it into array.
* **np.fromiter(iterable_obj,dtype=data_type)** ---> creates an array from an Iterable Object

In [3]:
import numpy as np

In [4]:
print(np.__version__)  # to check the version of the numoy
print(np.__doc__)  # to check the documentation of numpy

2.2.3

NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particu

In [5]:
arr=np.array((4,66,9,6,44,58,5,22,3),dtype=np.int32)  #A numpy array of data type int32
print(arr)  #Array stores data of the same type

[ 4 66  9  6 44 58  5 22  3]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.ndim  #function to check the dimesnion of the array

1

In [8]:
#Creating a 2D Array
arr_2d=np.array([[4,54,6],[1,4,4],[1,8,9],[7,22,3]])
print(arr_2d)
print(arr_2d.ndim)  #prinnts the dimesnion of the array
print(arr_2d.shape)  #prints the shape of the array  i.e rows x columns

[[ 4 54  6]
 [ 1  4  4]
 [ 1  8  9]
 [ 7 22  3]]
2
(4, 3)


In [9]:
arr1=np.array([4,6,8,9]); arr2=np.array([4,9,6,3])
arr1+arr2  # + operator leads to an corresponding elemental scalar addition of the numbers in the both the array (provided the shape of the array is same)

array([ 8, 15, 14, 12])

In [10]:
arr

array([ 4, 66,  9,  6, 44, 58,  5, 22,  3], dtype=int32)

In [11]:
arr[5]  #accesing the 5th index of the array

np.int32(58)

In [12]:
arr[2]= 560 #changing the value of the 2nd index of the array
print(arr)

[  4  66 560   6  44  58   5  22   3]


In [13]:
#Trying to modify an ith index eleemnt of the array but of diffrerent data type
arr[3]=3.141 #It will truncate the decimal part of the float number and will store the integer part of the number
arr

array([  4,  66, 560,   3,  44,  58,   5,  22,   3], dtype=int32)

In [14]:
#Creating an 4 x 5 array with the help of a function
arr3=np.fromfunction(lambda a,b : a**b , (4,5), dtype=int)  #This will create a 4 x 5 array with the help of a function
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[ 1  0  0  0  0]
 [ 1  1  1  1  1]
 [ 1  2  4  8 16]
 [ 1  3  9 27 81]]
2
(4, 5)


In [15]:
np.fromstring("APPLE, BANANA, CHERRY", sep=",")  #This will create an array of the string

C:\Users\abirm\AppData\Local\Temp\ipykernel_10172\1456927273.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("APPLE, BANANA, CHERRY", sep=",")  #This will create an array of the string


array([], dtype=float64)

In [16]:
np.fromstring("26,5,8,99,6,44,7,8", sep=",")  #bEST WORKS WHEN THE STRING SQQUENCE IS OF THE SAME DATA TYPE like all integer or float

array([26.,  5.,  8., 99.,  6., 44.,  7.,  8.])

In [17]:
#Creating an array from an interable object
iterable=map(lambda x: x*x , range(10,21,2))  #Creating a map object with the help of lambda function
arr4=np.fromiter(iterable, dtype=int)  #Creating an array from the map object
arr4

array([100, 144, 196, 256, 324, 400])

## **02. Numpy Advance 1**

* **<arr_obj>[:]= <Changed_constant_value>** ---> To change all the elements of an Array at once with a fixed value

* **np.eye** ---> Offers more flexibility in creating matrices with ones on a specific diagonal.
    Use np.eye when you need more control over the dimensions of the matrix or want to place the ones on a diagonal other than the main diagonal.

* **arr_obj.T** --> performs the transpose of a Matrix

* **np.arange()** --->  arange(...)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None) Return evenly spaced values within a given interval.

In [18]:
np.arange(0,100,5)  #Stop is exclusive , #It won't care about the length only will care about the step size

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [19]:
# help(np.arange)

* **np.linespace(start,stop,datapoints_frequency)** ----> Returns evenly spaced numbers over a specified interval

In [20]:
np.linspace(0,100,20) #It will create an array of 20 elements from 0 to 100 both inclusive with an equal step size decided by the function
#But sometimes may optionally exclude the endpoint

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

* **Creating an Array of all Zeros and All Oness**

In [21]:
arr5=np.zeros((3,3),dtype=float)  #Creating a Null MAatrix of 3X3
print(arr5)
print(arr5.ndim)
print(arr5.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2
(3, 3)


In [22]:
#Creating an matrix of 4 x 5 of all ones
arr6=np.ones((4,5),dtype=float)
print(arr6)
print(arr6.ndim)
print(arr6.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
2
(4, 5)


In [23]:
#Creating a 3D matrix of 2x3x4 
arr7=np.ones((2,3,4))
print(arr7)
print(arr7.ndim)
print(arr7.shape)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
3
(2, 3, 4)


In [24]:
arr8=np.empty((2,3))
arr8

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.11260348e-306, 1.89146896e-307, 7.56571288e-307]])

In [25]:
print(arr6)
print(arr6.T)  #Creating transpose of the arr6 matrix

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
print(arr7.shape)  #Original 3D matrix
print(arr7,end="\n\n")
print(arr7.T)
print(arr7.T.shape)  #Transposing a 3D Matrix

(2, 3, 4)
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
(4, 3, 2)


### **2.1 Random Ways to Populate an Array**

In [27]:
np.random.rand(5,6) #Creates a array of szie 5x6 with random numbers [0,1)]

array([[0.14965231, 0.20538078, 0.59030337, 0.37553498, 0.76844292,
        0.45489991],
       [0.5046719 , 0.53838024, 0.71475229, 0.55441667, 0.30529299,
        0.14231026],
       [0.04418784, 0.97511743, 0.83060383, 0.3808985 , 0.7647674 ,
        0.00503237],
       [0.19049284, 0.87075786, 0.96274731, 0.21439995, 0.37935248,
        0.91395153],
       [0.65689555, 0.69402431, 0.70327172, 0.16414015, 0.62388222,
        0.25100142]])

In [28]:
np.random.randint(low=4,high=15,size=(5,5)) #This creates an Array of size 5 x 5 with random numbers between [low,high)]

array([[12,  7, 11, 11, 12],
       [ 8,  8,  4, 14,  9],
       [ 7, 10,  6,  8, 14],
       [14,  8, 14, 13, 12],
       [12,  9,  4,  5, 11]], dtype=int32)

In [29]:
np.random.randn(5,5)  #This creates an array of size 5 x 5 with random numbers from the standard normal distribution

array([[ 0.22331464,  0.01888711, -0.53423419, -1.22071282, -0.93639665],
       [-0.45207567,  0.61323537,  1.28027664,  1.07266361,  0.048715  ],
       [-1.2335847 , -0.87000725,  0.16792103, -1.14367533,  0.49568344],
       [-2.03998689, -0.13645952,  0.28099293, -2.17260878,  1.13261771],
       [-1.06034378,  0.24142067,  1.06129154, -0.48216265,  1.04884702]])

### **2.2 Re-Shaping an Array**
* Basically changing the dimesnion of the array
* reshaping only possible when re-shape dimensions are multiple to the the number of elements in the Array
* case when you dont know in reshape what should be the column count or row count just add -1 (or any -ve value)to the respective position
* **arr.reshape(12, 1).base** ---> to see the original array

In [30]:
print(arr3)
print("Shape of the array ",arr3.shape)
print("Array Size or Number of Elements in the array ",arr3.size)

[[ 1  0  0  0  0]
 [ 1  1  1  1  1]
 [ 1  2  4  8 16]
 [ 1  3  9 27 81]]
Shape of the array  (4, 5)
Array Size or Number of Elements in the array  20


In [31]:
#Reshaping the above array from 4x5 to 10x2
arr3.reshape(10,2)

array([[ 1,  0],
       [ 0,  0],
       [ 0,  1],
       [ 1,  1],
       [ 1,  1],
       [ 1,  2],
       [ 4,  8],
       [16,  1],
       [ 3,  9],
       [27, 81]])

In [32]:
try :
    arr3.reshape(12,55)  #Trying to reshape with invalid shape of the array
except Exception as e:
    print("Not a valid shape for the array",e)

Not a valid shape for the array cannot reshape array of size 20 into shape (12,55)


In [33]:
#In case someone does not know the number of rows or columns in the array or want to see the actual view of the array
print(arr6.shape)
print(arr6)
print("New Re-shape of the Array",arr6.reshape(2,-1))  #Leaving the column entry to numpy

(4, 5)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
New Re-shape of the Array [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [34]:
new_arr=arr6.reshape(2,10)
print(new_arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [35]:
new_arr.reshape(2,10).base  #This shows the view of the actual base array shape

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### **2.3 Slicing and Indexing an Array**
* arr[ith] --> Gives all the elemnt of ith row as an NumPy Array
* arr[ith][jth] ---> Gives the elemnt present at the (ith row and jth column i 2D )
* arr[i:j]  ---> gives all the rows from ith to (j-1)th row of the matrix 


In [36]:
test_arr=np.random.randint(low=1,high=51,size=(8,3))
print("Our Array \n ",test_arr)
print(f"Size of the Array : {test_arr.size}")
print(f"Shape of the Array : {test_arr.shape}")
print(f"Dimension of the Array : {test_arr.ndim}")

Our Array 
  [[ 3  8  8]
 [42 23 23]
 [25  2 36]
 [40 16 27]
 [50  5 22]
 [41 33 48]
 [ 1  8 41]
 [36  1 16]]
Size of the Array : 24
Shape of the Array : (8, 3)
Dimension of the Array : 2


In [37]:
#Fetching the first 4 rows of the Matrix
test_arr[:4]

array([[ 3,  8,  8],
       [42, 23, 23],
       [25,  2, 36],
       [40, 16, 27]], dtype=int32)

In [38]:
#Fecth all the elements of the 2nd column
test_arr[:,1]

array([ 8, 23,  2, 16,  5, 33,  8,  1], dtype=int32)

In [39]:
#Create a sub-matrix of last 3 rows and last 2 columns
test_arr[-3:,-2:]

array([[33, 48],
       [ 8, 41],
       [ 1, 16]], dtype=int32)

In [40]:
#Testing out some condition on the array itself
test_arr>12

array([[False, False, False],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True],
       [False, False,  True],
       [ True, False,  True]])

In [41]:
test_arr[test_arr<12]

array([3, 8, 8, 2, 5, 1, 8, 1], dtype=int32)

### **2.4 Index-Wise Arithmetic Operations , Overall Mathematical Operations  and Matrix Multiplication**
* For index wise Arithmetic Operations the shape of the participating array should be the same else exception will be raised
* For Matrix Mul you know the rule :)

In [42]:
a=np.random.randint(low=10,high=61,size=(6,6))
b=np.random.randint(low=7,high=31,size=(6,6))
c=np.random.randint(low=-3,high=11,size=(6,4))

print(f"MATRIX 1 : {a} \n MATRIX 2 : {b} \n MATRIX 3 : {c}")

MATRIX 1 : [[52 30 58 57 44 44]
 [29 23 56 29 26 10]
 [36 49 55 60 37 39]
 [50 40 56 10 48 56]
 [48 37 54 58 24 16]
 [35 38 18 13 58 32]] 
 MATRIX 2 : [[24 20 20  9 21 21]
 [10 27  9 26 27 16]
 [23 28 22 18 27  9]
 [10 13  8 10 10 28]
 [18 26 26 24 10 21]
 [ 9 17 15  8 25 23]] 
 MATRIX 3 : [[ 0  8  2 10]
 [ 2  9  6  0]
 [ 6 10  4 -2]
 [ 7 -1  0  1]
 [10  4 -1  3]
 [ 8  2  1  4]]


In [43]:
#Performing Indexwise + , - , * , /
print(f"Addition of the Matrices : \n {a+b}")
print(f"Subtraction of the Matrices : \n {a-b}")
print(f"Multiplication of the Matrices : \n {a*b}")
print(f"Division of the Matrices : \n {a/b}")

Addition of the Matrices : 
 [[76 50 78 66 65 65]
 [39 50 65 55 53 26]
 [59 77 77 78 64 48]
 [60 53 64 20 58 84]
 [66 63 80 82 34 37]
 [44 55 33 21 83 55]]
Subtraction of the Matrices : 
 [[28 10 38 48 23 23]
 [19 -4 47  3 -1 -6]
 [13 21 33 42 10 30]
 [40 27 48  0 38 28]
 [30 11 28 34 14 -5]
 [26 21  3  5 33  9]]
Multiplication of the Matrices : 
 [[1248  600 1160  513  924  924]
 [ 290  621  504  754  702  160]
 [ 828 1372 1210 1080  999  351]
 [ 500  520  448  100  480 1568]
 [ 864  962 1404 1392  240  336]
 [ 315  646  270  104 1450  736]]
Division of the Matrices : 
 [[2.16666667 1.5        2.9        6.33333333 2.0952381  2.0952381 ]
 [2.9        0.85185185 6.22222222 1.11538462 0.96296296 0.625     ]
 [1.56521739 1.75       2.5        3.33333333 1.37037037 4.33333333]
 [5.         3.07692308 7.         1.         4.8        2.        ]
 [2.66666667 1.42307692 2.07692308 2.41666667 2.4        0.76190476]
 [3.88888889 2.23529412 1.2        1.625      2.32       1.39130435]]


In [44]:
#Generating the Sqrt and log10 of the matrix
print(f"Square Root of the Matrix : \n {np.sqrt(a)}")
print(f"Log10 of the Matrix : \n {np.log10(a)}")

Square Root of the Matrix : 
 [[7.21110255 5.47722558 7.61577311 7.54983444 6.63324958 6.63324958]
 [5.38516481 4.79583152 7.48331477 5.38516481 5.09901951 3.16227766]
 [6.         7.         7.41619849 7.74596669 6.08276253 6.244998  ]
 [7.07106781 6.32455532 7.48331477 3.16227766 6.92820323 7.48331477]
 [6.92820323 6.08276253 7.34846923 7.61577311 4.89897949 4.        ]
 [5.91607978 6.164414   4.24264069 3.60555128 7.61577311 5.65685425]]
Log10 of the Matrix : 
 [[1.71600334 1.47712125 1.76342799 1.75587486 1.64345268 1.64345268]
 [1.462398   1.36172784 1.74818803 1.462398   1.41497335 1.        ]
 [1.5563025  1.69019608 1.74036269 1.77815125 1.56820172 1.59106461]
 [1.69897    1.60205999 1.74818803 1.         1.68124124 1.74818803]
 [1.68124124 1.56820172 1.73239376 1.76342799 1.38021124 1.20411998]
 [1.54406804 1.5797836  1.25527251 1.11394335 1.76342799 1.50514998]]


In [45]:
#Finding the sum of all the elements in the Array/Matrix
print(f"Matrix : {c}")
print(f"\n Sum of all the Elements present in the Array : {np.sum(c)}")

Matrix : [[ 0  8  2 10]
 [ 2  9  6  0]
 [ 6 10  4 -2]
 [ 7 -1  0  1]
 [10  4 -1  3]
 [ 8  2  1  4]]

 Sum of all the Elements present in the Array : 93


In [46]:
#Performing actual Matrix Mul

#1st way : More modern and Pythonic way using the @ operator
result1=a @ b @ c
print(result1)
print(result1.shape)

[[171968 169837  65354  80216]
 [106445 108639  41911  50229]
 [167282 160186  61872  76035]
 [164282 164080  62768  74184]
 [142152 139793  53699  67615]
 [122071 119396  47084  53868]]
(6, 4)


In [47]:
#2nd Way : Using the dot function , a more legacy way 
np.dot(np.dot(a,b),c)  #Same answers but two diffrerent ways

array([[171968, 169837,  65354,  80216],
       [106445, 108639,  41911,  50229],
       [167282, 160186,  61872,  76035],
       [164282, 164080,  62768,  74184],
       [142152, 139793,  53699,  67615],
       [122071, 119396,  47084,  53868]], dtype=int32)

sum ,log , max ,min

### **2.5 Creating Default and Custom Identity Matrix**
* **np.eye(row,col,k,dtype)** ---> Use to create Custom Identity Matrix
    * Offers more flexibility in creating matrices with ones on a specific diagonal.
    Use np.eye when you need more control over the dimensions of the matrix or want to place the ones on a diagonal other than the main diagonal.
* **np.identity(n)** ---> helps to create a simple default unit/identity matrix

In [48]:
#Creating a bsic 4x4 unit Matrix
T=np.identity(4)
T

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
#Creating a 4x4 matrix with the diagonal elements as 1,2,3,4
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [50]:
#creating a custom 4x4 Unit Matrix
print(np.eye(3,4,k=1))  #k is the diagonal index
print("\n",np.eye(3,4,k=-1)) 
 # """ Takes two optional arguments:
#n (integer): Similar to np.identity, specifies the number of rows in the resulting matrix.
#m (integer, optional): Specifies the number of columns in the resulting matrix (defaults to n for a square matrix).
#k (integer, optional): Controls the position of the diagonal with ones. 
#By default (k=0), it places ones on the main diagonal. 
#Positive values shift the diagonal upwards, while negative values shift it downwards."""

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

 [[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


## **03. Numpy Advance 02**

In [124]:
arr1 = np.random.randint(1, 21, (4,4))
arr2 = np.random.randint(4, 8, (3,3))
arr3= np.random.rand(3,5)

### **3.1 Expanding and Reducing the Dimension of an Array**
* **arr_obj.flatten()** --> Return a copy of the array collapsed into one dimension.

* **np.expand_dims(arr_obj,axis=required axis)** ---> increases the dimension by 1 at provoided axis
  * Expand the shape of an array.
    Insert a new axis that will appear at the `axis` position in the expanded
    array shape.

* **np.squeeze(arr_obj,axis=None)** ---> Remove axes of length one from `arr_obj`.
* **np.repeat(arr_obj,n,axes=)** ---> repeat(a, repeats, axis=None)
    Repeat each element of an array after themselves
 

In [52]:
print(f"Matrix : {arr2}")
print(f"\n Shape of the Matrix : {arr2.shape}")
print(f"\n Size of the Matrix : {arr2.size}")
print("")
#Increasing the dimesnion of the arr2 by 1
print(f"New Expanded Matrix : \n {np.expand_dims(arr2, axis=2)}")
print(f"\n Shape of the Expanded Matrix : {np.expand_dims(arr2, axis=2).shape}")

Matrix : [[5 4 7]
 [4 5 4]
 [5 5 6]]

 Shape of the Matrix : (3, 3)

 Size of the Matrix : 9

New Expanded Matrix : 
 [[[5]
  [4]
  [7]]

 [[4]
  [5]
  [4]]

 [[5]
  [5]
  [6]]]

 Shape of the Expanded Matrix : (3, 3, 1)


In [53]:
arr2

array([[5, 4, 7],
       [4, 5, 4],
       [5, 5, 6]], dtype=int32)

In [54]:
#Reapeating the elements of arr2 column wise 3 times
np.repeat(arr2,3,axis=1)

array([[5, 5, 5, 4, 4, 4, 7, 7, 7],
       [4, 4, 4, 5, 5, 5, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 6, 6, 6]], dtype=int32)

### **3.2 Rolling an Array along a particluar axis or particular time**

In [55]:
help(np.roll)

Help on _ArrayFunctionDispatcher in module numpy:

roll(a, shift, axis=None)
    Roll array elements along a given axis.

    Elements that roll beyond the last position are re-introduced at
    the first.

    Parameters
    ----------
    a : array_like
        Input array.
    shift : int or tuple of ints
        The number of places by which elements are shifted.  If a tuple,
        then `axis` must be a tuple of the same size, and each of the
        given axes is shifted by the corresponding number.  If an int
        while `axis` is a tuple of ints, then the same value is used for
        all given axes.
    axis : int or tuple of ints, optional
        Axis or axes along which elements are shifted.  By default, the
        array is flattened before shifting, after which the original
        shape is restored.

    Returns
    -------
    res : ndarray
        Output array, with the same shape as `a`.

    See Also
    --------
    rollaxis : Roll the specified axis backwards, 

In [56]:
arr1

array([[ 7, 14, 17,  4],
       [ 3,  5, 15, 12],
       [13,  2,  6,  8],
       [16, 11, 11,  9]], dtype=int32)

In [57]:
np.roll(arr1,(2,1),axis=(1,0 )) #Rolling the elements of the array by 2 and 1 in the 1st and 2nd axis respectively

array([[11,  9, 16, 11],
       [17,  4,  7, 14],
       [15, 12,  3,  5],
       [ 6,  8, 13,  2]], dtype=int32)

In [58]:
np.roll(arr1,1)

array([[ 9,  7, 14, 17],
       [ 4,  3,  5, 15],
       [12, 13,  2,  6],
       [ 8, 16, 11, 11]], dtype=int32)

### **3.3 Some More Mathematical Operations**

In [59]:
arr1

array([[ 7, 14, 17,  4],
       [ 3,  5, 15, 12],
       [13,  2,  6,  8],
       [16, 11, 11,  9]], dtype=int32)

In [60]:
arr2

array([[5, 4, 7],
       [4, 5, 4],
       [5, 5, 6]], dtype=int32)

In [61]:
print(arr1 ^ arr2) #Bitwise XOR operation on the two arrays
print("\n",arr1 | arr2) #Bitwise OR operation on the two arrays

ValueError: operands could not be broadcast together with shapes (4,4) (3,3) 

In [ ]:
#Finding some basic statistics of the array
print(f"Mean of the Array : {np.mean(arr1)}")
print(f"Median of the Array : {np.median(arr1)}")
print(f"Standard Deviation of the Array : {np.std(arr1)}")
print(f"Variance of the Array : {np.var(arr1)}")

Mean of the Array : 1.8888888888888888
Median of the Array : 1.0
Standard Deviation of the Array : 1.0999438818457405
Variance of the Array : 1.2098765432098766


In [ ]:
#Squaring a matrix
print(arr1**2)  #1st Method

print(np.square(arr1))  #2nd Method

[[ 9  4  1]
 [ 1 16  9]
 [ 1  1  1]]
[[ 9  4  1]
 [ 1 16  9]
 [ 1  1  1]]


In [ ]:
#Perfroming modulus divison of arr1 and arr2
np.mod(arr1,arr2)

array([[3, 2, 1],
       [1, 4, 3],
       [1, 1, 1]], dtype=int32)

### **3.3 Sorting and Custom Search in Array**

* **sort(a, axis=-1, kind=None, order=None)** ----> Return a sorted copy of an array.
* a : array_like Array to be sorted.
* axis : int or None, optional  Axis along which to sort. If None, the array is flattened before
* kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optionalSorting algorithm. The default is 'quicksort'. Note that both 'stable' and 'mergesort' use timsort or radix sort under the covers and, in general, the actual implementation will vary with data type. The 'mergesort' option is retained for backwards compatibility.
*  order : str or list of str, optional When `a` is an array with fields defined, this argument specifies which fields to compare first, second, etc.  A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

In [ ]:
arr1

array([[ 4,  8, 19, 10],
       [20,  1,  4, 12],
       [ 7, 17,  8, 18],
       [ 7, 16,  9, 16]], dtype=int32)

In [ ]:
print(np.sort(arr1,axis=0))  #Sorting the array column wise
print("\n",np.sort(arr1,axis=1))  #Sorting the array row wise  #Default axis is 1

[[ 4  1  4 10]
 [ 7  8  8 12]
 [ 7 16  9 16]
 [20 17 19 18]]

 [[ 4  8 10 19]
 [ 1  4 12 20]
 [ 7  8 17 18]
 [ 7  9 16 16]]


In [ ]:
#Custom sorting based on required parameters/orders
# Use the `order` keyword to specify a field to use when sorting a structured array:

values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),('Galahad', 1.7, 38)]
dtype = [('name', 'S10'), ('height', float), ('age', int)]  #Creating a custom data type

A=np.array(values,dtype=dtype)
print(np.sort(A,order=['age', 'height']))   # Sort by age, then height if ages are equal:
print("D.type of the array A : ",A.dtype)

[(b'Galahad', 1.7, 38) (b'Lancelot', 1.9, 38) (b'Arthur', 1.8, 41)]
D.type of the array A :  [('name', 'S10'), ('height', '<f8'), ('age', '<i8')]


In [ ]:
np.count_nonzero(arr1)  #Counting the number of non-zero elements in the array

16

In [ ]:
#byteswap
arr1.byteswap()

array([[ 67108864, 134217728, 318767104, 167772160],
       [335544320,  16777216,  67108864, 201326592],
       [117440512, 285212672, 134217728, 301989888],
       [117440512, 268435456, 150994944, 268435456]], dtype=int32)

### **3.4 Matrix and Linear-Algebra**

In [62]:
import numpy.linalg as la
import numpy.matlib as mat

In [63]:
test=np.random.randint(1,11,size=5)
test

array([ 7,  8,  3,  7, 10], dtype=int32)

In [64]:
test=np.expand_dims(test,axis=0)
test  #Row Vector

array([[ 7,  8,  3,  7, 10]], dtype=int32)

In [65]:
test.T  #Transposing it to a column vector

array([[ 7],
       [ 8],
       [ 3],
       [ 7],
       [10]], dtype=int32)

In [66]:
A=np.array([[2,1,3],[3,0,1],[1,2,5]])
B=np.array([[5],[-4],[14]])
print(f"Coefficient Matrix : {A} \n RHS Matrix : {B}")

Coefficient Matrix : [[2 1 3]
 [3 0 1]
 [1 2 5]] 
 RHS Matrix : [[ 5]
 [-4]
 [14]]


In [ ]:
try:
    print(f"Inverse of the Coefficient Matrix : \n {la.inv(A)}")
except Exception as e:
    print("Matrix is not invertible",e)
finally:
    # print(f"Solution of the Linear Equation : \n {la.inv(A) @ B}")
    print(f"Determinant of the Coefficient Matrix : {la.det(A)}")
    print(f"Rank of the Coefficient Matrix : {la.matrix_rank(A)}")
    print(f"Eigen Values of the Coefficient Matrix : {la.eig(A)}")
    #print(f"\n Eigen Vectors of the Coefficient Matrix : {la.eig(A)}")

Matrix is not invertible Singular matrix
Determinant of the Coefficient Matrix : 0.0
Rank of the Coefficient Matrix : 2
Eigen Values of the Coefficient Matrix : EigResult(eigenvalues=array([1.99840144e-15, 2.98437881e-01, 6.70156212e+00]), eigenvectors=array([[-0.13018891, -0.22789804,  0.55503377],
       [-0.91132238, -0.87758544,  0.36033844],
       [ 0.39056673,  0.42178937,  0.7497291 ]]))

 Eigen Vectors of the Coefficient Matrix : EigResult(eigenvalues=array([1.99840144e-15, 2.98437881e-01, 6.70156212e+00]), eigenvectors=array([[-0.13018891, -0.22789804,  0.55503377],
       [-0.91132238, -0.87758544,  0.36033844],
       [ 0.39056673,  0.42178937,  0.7497291 ]]))


In [ ]:
la.solve(A,B)  #solve method is only able to solve matrix with full rank , i.e |A|!=0
#This will raise error if the matrix is not invertible

In [71]:
#Computing the rank,trace,det,inverse,eigen value and eigen vector of a diagonal matrix
dia=np.diag([3,6,7,9])
print(f"Diagonal Matrix : \n {dia}")

Diagonal Matrix : 
 [[3 0 0 0]
 [0 6 0 0]
 [0 0 7 0]
 [0 0 0 9]]


In [73]:
print(f"Rank of the Diagonal Matrix : {la.matrix_rank(dia)}")  #Rank of the diagonal matrix
print(f"Trace of the Matrix {la.trace(dia)}")  #Trace of the matrix
print(f"Determinant of the Matrix : {la.det(dia)}")  #Determinant of the matrix
print(f"Eigen Values of the Matrix : \n {la.eig(dia)}")  #Eigen Values of the matrix

Rank of the Diagonal Matrix : 4
Trace of the Matrix 25
Determinant of the Matrix : 1133.9999999999998
Eigen Values of the Matrix : 
 EigResult(eigenvalues=array([3., 6., 7., 9.]), eigenvectors=array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]))


In [102]:
arr5=np.vstack((arr1,arr1))
arr5

array([[ 7, 14, 17,  4],
       [ 3,  5, 15, 12],
       [13,  2,  6,  8],
       [16, 11, 11,  9],
       [ 7, 14, 17,  4],
       [ 3,  5, 15, 12],
       [13,  2,  6,  8],
       [16, 11, 11,  9]], dtype=int32)

In [88]:
arr5[0:6:2]  #Starting from 0th index and going till 5th (6-1) index with a step size of 2

array([[ 7, 14, 17,  4],
       [13,  2,  6,  8],
       [ 7, 14, 17,  4]], dtype=int32)

### **3.5 Extra's**

* **Adding / Removing Elements from a Numpy array**
    * **np.append(arr_obj,(insert_object))**
    * **np.insert(arr_obj,position,insert_val/tuple)**
    * **delete(arr, obj, axis=None)** Return a new array with sub-arrays along an axis deleted.

* **Changing the DataType of the Array** ---> arr_obj.astype(<new_dtype>)

In [104]:
print(f"Initial Array : \n {arr5}")
print(f"inital Shape of the Array : {arr5.shape}")
#Matrix after adding two new rows
arr5=np.append(arr5,[[99,4,99,4]],axis=0)  #Append is not an in-place object modifer
print(f"New Array : \n {arr5}")
print(f"New Shape of the Array : {arr5.shape}")

Initial Array : 
 [[ 7 14 17  4]
 [ 3  5 15 12]
 [13  2  6  8]
 [16 11 11  9]
 [ 7 14 17  4]
 [ 3  5 15 12]
 [13  2  6  8]
 [16 11 11  9]
 [99  4 99  4]]
inital Shape of the Array : (9, 4)
New Array : 
 [[ 7 14 17  4]
 [ 3  5 15 12]
 [13  2  6  8]
 [16 11 11  9]
 [ 7 14 17  4]
 [ 3  5 15 12]
 [13  2  6  8]
 [16 11 11  9]
 [99  4 99  4]
 [99  4 99  4]]
New Shape of the Array : (10, 4)


In [106]:
arr5=np.insert(arr5,2,[1,2,3,4],axis=0)  #Inserting a new row at the 2nd index of the array
arr5=np.insert(arr5,4,[1,6,5,4,7,8,9,6,3,1,2],axis=1) #Inserting a new column at the 4th index of the array

In [110]:
#Deleting the 3rd row and the 3rd column of the array
print(f"Shape of Array before deletion : {arr5.shape}")
arr5=np.delete(arr5,2,axis=0)  #This is not an inplace object modifier , it will return a new array
arr5=np.delete(arr5,2,axis=1)
print(f"Shape of Array after deletion : {arr5.shape}")
print(f"New Array : \n {arr5}")

Shape of Array before deletion : (11, 5)
Shape of Array after deletion : (10, 4)
New Array : 
 [[ 7 14  4  1]
 [ 3  5 12  6]
 [13  2  8  4]
 [16 11  9  7]
 [ 7 14  4  8]
 [ 3  5 12  9]
 [13  2  8  6]
 [16 11  9  3]
 [99  4  4  1]
 [99  4  4  2]]


In [114]:
#Changing the data type of the arr5 from int64 to complex
print(f"Data Type of the Array : {arr5.dtype}")
arr5.astype(complex)  #Not an inplace object modifier

Data Type of the Array : int64


array([[ 7.+0.j, 14.+0.j,  4.+0.j,  1.+0.j],
       [ 3.+0.j,  5.+0.j, 12.+0.j,  6.+0.j],
       [13.+0.j,  2.+0.j,  8.+0.j,  4.+0.j],
       [16.+0.j, 11.+0.j,  9.+0.j,  7.+0.j],
       [ 7.+0.j, 14.+0.j,  4.+0.j,  8.+0.j],
       [ 3.+0.j,  5.+0.j, 12.+0.j,  9.+0.j],
       [13.+0.j,  2.+0.j,  8.+0.j,  6.+0.j],
       [16.+0.j, 11.+0.j,  9.+0.j,  3.+0.j],
       [99.+0.j,  4.+0.j,  4.+0.j,  1.+0.j],
       [99.+0.j,  4.+0.j,  4.+0.j,  2.+0.j]])

In [117]:
print(np.sum(arr5,axis=0) ) #Finding the sum of the columns of the array
print(np.sum(arr5,axis=1)) #Finding the sum of the rows of the array

[276  72  74  47]
[ 26  26  27  43  33  29  29  39 108 109]


In [125]:
print(arr3)
arr3=np.append(arr3,[[1,2,3,4,5]],axis=0)
print("\n ",arr3)
print(arr3.shape)

[[0.14393671 0.55893984 0.49242142 0.62148133 0.4377906 ]
 [0.45941151 0.49869793 0.04930766 0.39297389 0.62791816]
 [0.17729074 0.94662743 0.78688006 0.60481618 0.26588951]]

  [[0.14393671 0.55893984 0.49242142 0.62148133 0.4377906 ]
 [0.45941151 0.49869793 0.04930766 0.39297389 0.62791816]
 [0.17729074 0.94662743 0.78688006 0.60481618 0.26588951]
 [1.         2.         3.         4.         5.        ]]
(4, 5)


In [ ]:
arr5 @ arr3  #same as np.dot(arr5,arr3)

array([[ 9.14848108, 16.68085958, 10.2847775 , 16.2712685 , 17.9189464 ],
       [10.85635659, 27.52983835, 29.16636329, 35.08710758, 37.64363666],
       [ 8.20832621, 23.83663322, 24.79513429, 29.70373453, 29.07423015],
       [15.95213067, 36.94836151, 36.5030476 , 47.70975972, 51.30475485],
       [16.14848108, 30.68085958, 31.2847775 , 44.2712685 , 52.9189464 ],
       [13.85635659, 33.52983835, 38.16636329, 47.08710758, 52.64363666],
       [10.20832621, 27.83663322, 30.79513429, 37.70373453, 39.07423015],
       [11.95213067, 28.94836151, 24.5030476 , 31.70975972, 31.30475485],
       [17.7965435 , 63.11634547, 55.09447178, 69.51781222, 51.91649987],
       [18.7965435 , 65.11634547, 58.09447178, 73.51781222, 56.91649987]])

In [ ]:
np.dot(arr5,arr3)  #same as arr5 @ arr3

array([[ 9.14848108, 16.68085958, 10.2847775 , 16.2712685 , 17.9189464 ],
       [10.85635659, 27.52983835, 29.16636329, 35.08710758, 37.64363666],
       [ 8.20832621, 23.83663322, 24.79513429, 29.70373453, 29.07423015],
       [15.95213067, 36.94836151, 36.5030476 , 47.70975972, 51.30475485],
       [16.14848108, 30.68085958, 31.2847775 , 44.2712685 , 52.9189464 ],
       [13.85635659, 33.52983835, 38.16636329, 47.08710758, 52.64363666],
       [10.20832621, 27.83663322, 30.79513429, 37.70373453, 39.07423015],
       [11.95213067, 28.94836151, 24.5030476 , 31.70975972, 31.30475485],
       [17.7965435 , 63.11634547, 55.09447178, 69.51781222, 51.91649987],
       [18.7965435 , 65.11634547, 58.09447178, 73.51781222, 56.91649987]])

In [134]:
np.multiply(arr3,arr3)  #Normal corresponding element wise multiplication of two arrays
# np.multiply() is different from actual matrix multiplication

array([[2.07177771e-02, 3.12413743e-01, 2.42478858e-01, 3.86239047e-01,
        1.91660608e-01],
       [2.11058935e-01, 2.48699622e-01, 2.43124582e-03, 1.54428478e-01,
        3.94281210e-01],
       [3.14320073e-02, 8.96103497e-01, 6.19180225e-01, 3.65802609e-01,
        7.06972302e-02],
       [1.00000000e+00, 4.00000000e+00, 9.00000000e+00, 1.60000000e+01,
        2.50000000e+01]])